# Generated by Django 4.2.4 on 2023-09-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='descriptions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duratino',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='end_movie',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_movie',
            field=models.DateField(),
        ),
    ]
