# Generated by Django 4.2.4 on 2023-09-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tickets', '0003_ticket_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='club_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.clubcard'),
        ),
    ]
