# Generated by Django 4.2.4 on 2023-09-26 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0003_movie_descriptions_movie_duratino_movie_year_and_more'),
        ('tickets', '0004_ticket_club_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.order'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.seat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='show_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.showtime'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
